version: '3'
services:
  app:
    container_name: big_dipper
    restart: always
    image: trustory/explorer
    ports:
      - '3000:3000'
    links:
      - mongo
    volumes:
      - ./settings.json:/config/settings.json
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://root:example@mongo:27017/meteor?authSource=admin
  mongo:
    container_name: big_dipper_mongo
    image: mongo
    ports:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
